In [ ]:
6.989;
19.424

In [1]:
import numpy as np

In [5]:
maj=np.linspace(0.001,6.99,11);
minb=np.linspace(0.001,19.424,11);

In [6]:
maj

array([1.0000e-03, 6.9990e-01, 1.3988e+00, 2.0977e+00, 2.7966e+00,
       3.4955e+00, 4.1944e+00, 4.8933e+00, 5.5922e+00, 6.2911e+00,
       6.9900e+00])

In [7]:
minb

array([1.00000e-03, 1.94330e+00, 3.88560e+00, 5.82790e+00, 7.77020e+00,
       9.71250e+00, 1.16548e+01, 1.35971e+01, 1.55394e+01, 1.74817e+01,
       1.94240e+01])

In [8]:
r=np.vstack((maj,minb))

In [14]:
r.T

array([[1.00000e-03, 1.00000e-03],
       [6.99900e-01, 1.94330e+00],
       [1.39880e+00, 3.88560e+00],
       [2.09770e+00, 5.82790e+00],
       [2.79660e+00, 7.77020e+00],
       [3.49550e+00, 9.71250e+00],
       [4.19440e+00, 1.16548e+01],
       [4.89330e+00, 1.35971e+01],
       [5.59220e+00, 1.55394e+01],
       [6.29110e+00, 1.74817e+01],
       [6.99000e+00, 1.94240e+01]])

In [ ]:
1.00000e-03 1.00000e-03
6.99900e-01 1.94330e+00
1.39880e+00 3.88560e+00
2.09770e+00 5.82790e+00
2.79660e+00 7.77020e+00
3.49550e+00 9.71250e+00
4.19440e+00 1.16548e+01
4.89330e+00 1.35971e+01
5.59220e+00 1.55394e+01
6.29110e+00 1.74817e+01
6.99000e+00 1.94240e+01